services:
  - type: web
    name: pallet-builder
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build && cd ..
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NPM_CONFIG_PRODUCTION
        value: false
