services:
  - type: web
    name: pallet-builder-app
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build && cd .. && cp -r client/build/* public/
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
